version: "3.7"
services:
  prometheus:
    image: prom/prometheus:latest
    user: "${UID}:${GID}"
    volumes:
      - /data/monitoring/configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /data/monitoring/prometheus:/prometheus
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    user: "${UID}:${GID}"
    volumes:
      - /data/monitoring/configs/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /data/monitoring/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    links:
      - prometheus
  service-discovery:
    image: liqiangliu/prometheus-service-discovery:latest
    user: "${UID}:${GID}"
    environment:
    - MONGODB_HOST=192.168.1.88
    - PROMETHEUS_ADDR=http://prometheus:9090
    volumes:
      - /data/monitoring/configs/prometheus:/etc/prometheus
    ports:
      - 5555:5555